services:
  postgres:
    image: postgres
    container_name: kurs_bd
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin 
      - POSTGRES_PASSWORD=password  
      - POSTGRES_DB=db  
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql


    
